### PR TITLE
Improve datatables

### PR DESCRIPTION
**Pull request by demenech**
Ticket: https://github.com/datopian/datahub-next/issues/29

## Changes:
- Data components are now renamed to .tsx files
- Table component, functions extracted to lib files
- Data tables
  - Add basic pagination 
  - Add basic global search
  - Add basic sorting

ss-2023-03-06-18:37:50
ss-2023-03-06-18:38:11
ss-2023-03-06-18:38:27

### CODE REVIEW

**Comment by demenech** [comment]
Hey @rufuspollock 
Fixed, it's now deploying and passing the tests. All I did was remove tsconfig. The .tsx files seem to be working fine even without it.

Just for the record, when trying to fix tsconfig I ended up with this exact same issue: https://github.com/datopian/next.datahub.io/pull/74

Check out the preview: https://83aa2389.datahub-next.pages.dev/tools/view

**Comment by olayway** [comment]
> Just for the record, when trying to fix tsconfig I ended up with this exact same issue: https://github.com/datopian/next.datahub.io/pull/74

@demenech the issue comes from the fact that we're not using the most recent Flowershow template, where this has been solved. We need to have a separate `tsconfig.mdx.json` file with:

```
  "compilerOptions": {
    "jsx": "react"
  }

```


and reference it in base `tsconfig.json`. Check out how it's done in Flowershow template.

**Comment by olayway** [comment]
> @olayway i thought you would know 😄

Well, I didn't really get a chance to review this PR 😅

**Review by rufuspollock — COMMENTED** [review]
LGTM

**Comment by demenech** [comment]
Thank you for the clarification, @olayway

**Pull request merged**
