### PR TITLE
Introduce DataHub Toolkit Offer

### PR DESCRIPTION
**Pull request by sneha-sharma12**
- Datahub enterprise to Datahub Toolkit updated
- dms image changed
- CTA updated
- Updations in Solutions section
- Homepage & open-data page changed
- Moved enterprise to homepage & current homepage to open-data

### CODE REVIEW

**Comment by sneha-sharma12** [comment]
> @sneha-sharma12 thanks for this 👍🏼 one important note, now if I go to `/open-data` and click on Live demo button it just goes to the demo instance. Remember we did this that's now missing: #64

@anuveyatsu Done

**Comment by anuveyatsu** [comment]
thanks @sneha-sharma12 few more things:

- can we rename `components/enterprise` dir to `components/toolkit`?
- since we're shutting down datahub.io/enterprise page, we need to put a redirect so that visitors would go to `/toolkit`

**Comment by sneha-sharma12** [comment]
> thanks @sneha-sharma12 few more things:
> 
> * can we rename `components/enterprise` dir to `components/toolkit`?
> * since we're shutting down datahub.io/enterprise page, we need to put a redirect so that visitors would go to `/toolkit`

@anuveyatsu Updated

**Review by anuveyatsu — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
